<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ng nhp_lnXdpd</name>
   <tag></tag>
   <elementGuidId>fb25d91c-bc40-4bcd-a0ee-a31a24ae6665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lnXdpd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Google']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>948f530a-be95-4f9d-8133-64a486e5a81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnXdpd</value>
      <webElementGuid>4da59e36-dfdd-4669-8ae4-f6594616a37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>e149be10-2500-464b-bd4a-5d4caa7c7f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>ec3cae38-b5a7-4055-85b7-4c33cd0cf16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png</value>
      <webElementGuid>c90586d9-6742-4c6c-9406-aa703801b9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png 1x, /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png 2x</value>
      <webElementGuid>ebf68bb7-8205-42a3-9052-76c1dc30ca29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>272</value>
      <webElementGuid>6b853e3c-95f7-41d5-babd-ab61403708c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0395001e-b731-43ea-8f84-9a3754c1f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frt</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0cbaa918-c8a9-4d6b-89bf-365312ba05cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 LLD4me yr19Zb LS8OJ&quot;]/div[@class=&quot;k1zIA rSk4se&quot;]/img[@class=&quot;lnXdpd&quot;]</value>
      <webElementGuid>2fa33551-780b-4c95-87b0-f0a8a5987352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>1d816c37-016a-4e3f-ae5b-5a5463a9f618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>507ae61c-c9bd-47d4-91dc-d605b592a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Google' and @src = '/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png']</value>
      <webElementGuid>4be5a3ea-a8db-413e-8e36-56fd8ecb0c0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
